### ISSUE TITLE
Base structure & requirements

### ISSUE THREAD

**Issue by jstoiko** [aml-org/amf-playground#22]
## Structure
-header has:
  - left: [AML SVG logo](https://github.com/aml-org/a-ml/blob/develop/images/AML_white.svg)
  - right: dropdown menu linking different demos, prefixed by text: "Demo: "

## Requirements
- host on GH pages
- reuse [amf-playground](https://github.com/aml-org/amf-playground) as a base for html/visual libraries/etc
- use new a.ml [CSS](https://github.com/aml-org/a-ml/blob/stg/css/style.scss) - see [current staging site](https://stg.a.ml)
- use AMF (`amf-client-js`) directly
- use same [Monaco Editor and CSS](https://github.com/aml-org/a-ml/tree/stg/min/vs) as on new a.ml site
- enable syntax highlighting in all text editors (using AMF to validate)

**Comment by postatum** [comment]
- [ ] header has: left: AML SVG logo
- [ ] header has: right: dropdown menu linking different demos, prefixed by text: "Demo: "
- [ ] host on GH pages
- [ ] reuse amf-playground as a base for html/visual libraries/etc
- [ ] use new a.ml CSS - see current staging site
- [ ] use AMF (amf-client-js) directly
- [ ] use same Monaco Editor and CSS as on new a.ml site
- [ ] enable syntax highlighting in all text editors (using AMF to validate)

**Comment by postatum** [comment]
@jstoiko 

> enable syntax highlighting in all text editors (using AMF to validate)

Syntax highlighting is already implemented by Monaco editor + RAML syntax profile. Why/how do I use AMF for this?

**Comment by jstoiko** [comment]
Not sure but this is not RAML so it would have to be AML. How does syntax highlighting work? Is is a special Monaco-specific format? Can amf-client-js’s validation function be plugged somehow?

**Comment by postatum** [comment]
I just noticed syntax colours are a bit different on AML staging so I used those instead of RAML staging ones.

> How does syntax highlighting work? Is is a special Monaco-specific format?
It's a "theme" defined in Monaco settings

> Can amf-client-js’s validation function be plugged somehow?
It's unnecessary and I'm not sure it's possible. Highlighting already works as on staging.

**Comment by postatum** [comment]
All done.

**Comment by postatum** [comment]
Will close this issue and address notes/feedback in new ones.
