### ISSUE TITLE
"Validation" demo

### ISSUE THREAD

**Issue by jstoiko** [aml-org/amf-playground#23]
- [x] add "Validation" link to top-right dropdown menu
- [x] use simple document as example: only a Dialect (no Vocabulary)
- [x] side by side view: Dialect vs Document
- [x] highlight validation errors in Document

**Comment by postatum** [comment]
@jstoiko 
>  use simple document as example: only a Dialect (no Vocabulary)

I'm not sure it's possible to define Dialect without using Vocabularies. If what I think is true, how do we allow users to create Dialects if they can't create Vocabularies?

**Comment by postatum** [comment]
Implemented and merged into `develop`. Not hosted on github pages yet.

**Comment by postatum** [comment]
hosted

**Comment by postatum** [comment]
Will close this issue and address notes/feedback in new ones.
