### ISSUE TITLE
"Visualization" demo

### ISSUE THREAD

**Issue by jstoiko** [aml-org/amf-playground#24]
- [x] add "Visualization" link to top-right dropdown menu
- [x] side-by-side view. Illustrate using a simple example e.g. Kubernetes "Pod" containers[1] vs graph of containers
- [x] left-side is the Monaco editor with two tabs: Document + Dialect
- [x] when a graph element is selected, highlight corresponding AML text in Document

[1] https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#pod-v1-core

**Comment by postatum** [comment]
@jstoiko I see some sort of API doc in [1]. Which part of that should be used as a simple example? It has to be an AML doc, right? Do I also write a Dialect for it?

**Comment by postatum** [comment]
@jstoiko
1. Should Document be editable?
2. Should Dialect be editable?

**Comment by jstoiko** [comment]
1. yes
2. yes

**Comment by postatum** [comment]
As discussed re
>  side-by-side view. Illustrate using a simple example e.g. Kubernetes "Pod" containers[1] vs graph of containers

Pick YAML file from here https://github.com/kubernetes/examples which starts with `apiVersion: v1` and describe its format as AML Dialect.

**Comment by postatum** [comment]
implemented, merged to master and hosted

**Comment by postatum** [comment]
Will close this issue and address notes/feedback in new ones.
