### ISSUE TITLE
Address Visualization feedback (pt.1)

### ISSUE THREAD

**Issue by postatum** [aml-org/amf-playground#26]
- [x] 1) the Document graph is not centered
- [x] 2) how come the Document graph only contains one relationship? i.e. document.yaml<encodes>Pod? shouldn't it show other nodes like containers? maybe it's the way the Dialect is written? feel free to ask Pedro and Antonio on Slack..
- [x] 3) the Dialect graph is cut off, could it be automatically zoomed (and centered)?
- [x] 4) if I zoom in or scroll right on the Dialect graph and switch back to the Document graph, I no longer see the graph because it is out of view. I think the view should be reset each time we click away.
- [x] 5) the arrow size on the Dialect graph is too large
- [x] 6) how come there are no boxes under each nodeMappings (e.g. under the `DescriptionDataNode` box, shouldn't there be apiVersion, kind, etc)? I guess this the same question as 2)

**Comment by postatum** [comment]
>  1) the Document graph is not centered

"Solved" this by aligning graph Left->Right instead of Top->Bottom. This alignment makes more sense for this example and centering doesn't look necessary.

**Comment by postatum** [comment]
4. Fixed here https://github.com/aml-org/amf-playground/commit/c6577a6eacb92c4478508c43ef62dbf76fc523ab

**Comment by postatum** [comment]
@jstoiko is it ok if graph links don't have labels like `--declares-->`?

Can it be just a directed graph/tree representing elements of document/dialect?

**Comment by jstoiko** [comment]
Fine by me.

**Comment by jstoiko** [comment]
The more I am thinking about it, the more I think something like https://bramp.github.io/js-sequence-diagrams/ may actually look better than the current visualization library. thoughts?

**Comment by postatum** [comment]
> The more I am thinking about it, the more I think something like https://bramp.github.io/js-sequence-diagrams/ may actually look better than the current visualization library. thoughts?

What feature of `js-sequence-diagrams` do you like exactly?
To me generated diagram looks very similar.

**Comment by postatum** [comment]
Note for myself regarding `1) the Document graph is not centered`:
Might want to restore `TB` direction of a graph and reuse fix x-centering fix from `raml-org/playground`

**Comment by postatum** [comment]
Another note for myself regarding small number of nodes in graphs (2, 6):
Graph implementation needs a rework. One way to do it might be to get list of all `DomainElement`s and parse their IDs to create a list of nodes.

```js
> model.findByType('http://a.ml/vocabularies/document#DomainElement').map(l => l.id)
[ 'http://a.ml/amf/default_document#/declarations/DescriptionDataNode',
  'http://a.ml/amf/default_document#/declarations/DescriptionDataNode/property/apiVersion',
  'http://a.ml/amf/default_document#/declarations/DescriptionDataNode/property/kind',
  'http://a.ml/amf/default_document#/declarations/DescriptionDataNode/property/metadata',
  'http://a.ml/amf/default_document#/declarations/DescriptionDataNode/property/spec',
  'http://a.ml/amf/default_document#/declarations/MountNode',
  'http://a.ml/amf/default_document#/declarations/MountNode/property/name',
  'http://a.ml/amf/default_document#/declarations/MountNode/property/mountPath',
  'http://a.ml/amf/default_document#/declarations/VolumeNode',
  'http://a.ml/amf/default_document#/declarations/VolumeNode/property/name',
  'http://a.ml/amf/default_document#/declarations/VolumeNode/property/emptyDir',
  'http://a.ml/amf/default_document#/declarations/EmptydirNode',
  'http://a.ml/amf/default_document#/declarations/EmptydirNode/property/medium',
  'http://a.ml/amf/default_document#/declarations/ContainerNode',
  'http://a.ml/amf/default_document#/declarations/ContainerNode/property/name',
  'http://a.ml/amf/default_document#/declarations/ContainerNode/property/image',
  'http://a.ml/amf/default_document#/declarations/ContainerNode/property/volumeMounts',
  'http://a.ml/amf/default_document#/declarations/ContainerNode/property/command',
  'http://a.ml/amf/default_document#/declarations/ContainerNode/property/args',
  'http://a.ml/amf/default_document#/declarations/SpecNode',
  'http://a.ml/amf/default_document#/declarations/SpecNode/property/restartPolicy',
  'http://a.ml/amf/default_document#/declarations/SpecNode/property/volumes',
  'http://a.ml/amf/default_document#/declarations/SpecNode/property/containers',
  'http://a.ml/amf/default_document#/declarations/MetadataNode',
  'http://a.ml/amf/default_document#/declarations/MetadataNode/property/name' ]
> model2.findByType('http://a.ml/vocabularies/document#DomainElement').map(l => l.id)
[ 'http://a.ml/amf/default_document#/',
  'http://a.ml/amf/default_document#/metadata',
  'http://a.ml/amf/default_document#/spec',
  'http://a.ml/amf/default_document#/spec/volumes/0',
  'http://a.ml/amf/default_document#/spec/volumes/0/emptyDir',
  'http://a.ml/amf/default_document#/spec/volumes/1',
  'http://a.ml/amf/default_document#/spec/volumes/1/emptyDir',
  'http://a.ml/amf/default_document#/spec/containers/0',
  'http://a.ml/amf/default_document#/spec/containers/0/volumeMounts/0',
  'http://a.ml/amf/default_document#/spec/containers/1',
  'http://a.ml/amf/default_document#/spec/containers/1/volumeMounts/0',
  'http://a.ml/amf/default_document#/spec/containers/1/volumeMounts/1' ]
```

**Comment by postatum** [comment]
Also I think `js-sequence-diagrams` won't work because a) it's made to draw sequence graphs and b) our logic is too tied with joinjs (clicks, events, etc).

**Comment by postatum** [comment]
All the changes are in `i26_visualization_feedback` branch.

**Comment by postatum** [comment]
re 2,6: another thing that may be useful is 
```js
        jsonld.flatten(parsed, (err, flattened) => {

        });
```

**Comment by postatum** [comment]
@jstoiko I've reworked graph nodes to address `2)`, `6)` in branch `i26_visualization_feedback_rework_graph`.
Please switch to it, run demo and let me know if you like it.

```sh
git fetch
git checkout i26_visualization_feedback_rework_graph
gulp serveVisualization
```

**Comment by jstoiko** [comment]
beautiful! let’s go with this.
